services:
  postgres:
    image: postgres:16
    container_name: postgres-grupo4
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: dossie_grupo4
    ports:
      - "${DB_PORT:-5433}:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
      - ./sql:/sql:ro
      - ./respostas:/respostas
    restart: unless-stopped

volumes:
  postgres_data:
