"""
config.py
=========

Configuration module for the ideal-point estimation pipeline (W-NOMINATE).

This module centralizes every tunable parameter and every filesystem path used
when building the canonical roll-call vote matrix. NO magic numbers should appear
anywhere else in the pipeline: import the constants from here instead.

The matrix produced by `prepare_votes_matrix.py` (using these constants) is the
OFFICIAL input for every future ideal-point estimation run. Changing a value
here changes the canonical input, so edits should be deliberate and documented.

All paths are expressed relative to the repository root so the pipeline can be
executed from the project base directory.
"""

from pathlib import Path

# ---------------------------------------------------------------------------
# Repository layout
# ---------------------------------------------------------------------------
# Root of the repository (this file lives in <root>/scripts/ideal_points/).
PROJECT_ROOT = Path(__file__).resolve().parents[2]

# Input: the standardized roll-call vote dataset (one row per deputy-vote).
INPUT_VOTES_CSV = PROJECT_ROOT / "dados_padronizados" / "votacoes_votos.csv"

# Input: roll-call level metadata (date, organ, approval, description).
# Used only to enrich the metadata outputs (e.g. the date of each roll call).
INPUT_VOTACOES_CSV = PROJECT_ROOT / "dados_padronizados" / "votacoes.csv"

# Output directory for every artifact generated by this pipeline step.
OUTPUT_DIR = PROJECT_ROOT / "dados_processados" / "ideal_points"

# Output files.
OUTPUT_MATRIX_CSV = OUTPUT_DIR / "votes_matrix.csv"
OUTPUT_MATRIX_FILTERED_CSV = OUTPUT_DIR / "votes_matrix_filtered.csv"
OUTPUT_VOTES_METADATA_CSV = OUTPUT_DIR / "votes_metadata.csv"
OUTPUT_DEPUTIES_METADATA_CSV = OUTPUT_DIR / "deputies_metadata.csv"
OUTPUT_SUMMARY_STATS_CSV = OUTPUT_DIR / "summary_statistics.csv"

# The standardized CSVs use a semicolon as the field separator.
CSV_SEPARATOR = ";"

# Sentinel used to represent a missing/ignored vote in CSV outputs.
# Pandas writes empty cells for NaN; we keep that convention so the matrix reads
# back cleanly as NA in both Python and R.
NA_REPRESENTATION = ""  # empty cell == NA

# ---------------------------------------------------------------------------
# Vote encoding
# ---------------------------------------------------------------------------
# Only "Sim" and "Nao" are treated as valid behavioral votes. Every other vote
# type ("Obstrucao", "Abstencao", "Artigo 17", etc.) is treated as missing (NA).
#
#   Sim -> 1
#   Nao -> 0
#   anything else -> NA
#
# No other values are ever written into the matrix.
VOTE_VALUE_MAP = {
    "Sim": 1,
    "Nao": 0,
}

# ---------------------------------------------------------------------------
# Filtering thresholds (the only knobs that change which rows/columns are kept)
# ---------------------------------------------------------------------------

# MIN_VALID_VOTES_PER_DEPUTY
# --------------------------
# Minimum number of valid (Sim/Nao) votes a deputy must have cast across the
# RETAINED roll calls to be kept in the filtered matrix. Deputies below this
# threshold contribute too little information to be reliably scaled and are
# marked for removal (they are NOT deleted from the unfiltered matrix).
MIN_VALID_VOTES_PER_DEPUTY = 20

# MIN_VALID_VOTES_PER_ROLLCALL
# ----------------------------
# Minimum number of valid (Sim/Nao) votes a roll call must contain to be kept.
# Roll calls with very low participation carry little discriminating power and
# are marked for removal.
MIN_VALID_VOTES_PER_ROLLCALL = 20

# MAX_UNANIMITY_RATE
# ------------------
# A roll call is considered "nearly unanimous" (and therefore non-discriminating)
# when the majority side accounts for at least this fraction of the valid votes.
# Such roll calls provide almost no information for separating deputies and are
# marked for removal. Value is a proportion in [0, 1]; 0.97 == 97%.
MAX_UNANIMITY_RATE = 0.97
