"""Table mapping for the local ETL."""

from . import cleaning as C


PARTIDOS_IDEOLOGIA = [
    {"sigla_partido": "AVANTE", "ideologia": "centro"},
    {"sigla_partido": "CIDADANIA", "ideologia": "centro"},
    {"sigla_partido": "MDB", "ideologia": "centro"},
    {"sigla_partido": "MISSAO", "ideologia": "centro"},
    {"sigla_partido": "NOVO", "ideologia": "direita"},
    {"sigla_partido": "PCDOB", "ideologia": "esquerda"},
    {"sigla_partido": "PDT", "ideologia": "esquerda"},
    {"sigla_partido": "PL", "ideologia": "direita"},
    {"sigla_partido": "PODE", "ideologia": "centro"},
    {"sigla_partido": "PP", "ideologia": "direita"},
    {"sigla_partido": "PRD", "ideologia": "centro"},
    {"sigla_partido": "PSB", "ideologia": "esquerda"},
    {"sigla_partido": "PSD", "ideologia": "centro"},
    {"sigla_partido": "PSDB", "ideologia": "centro"},
    {"sigla_partido": "PSOL", "ideologia": "esquerda"},
    {"sigla_partido": "PT", "ideologia": "esquerda"},
    {"sigla_partido": "PV", "ideologia": "esquerda"},
    {"sigla_partido": "REDE", "ideologia": "esquerda"},
    {"sigla_partido": "REPUBLICANOS", "ideologia": "direita"},
    {"sigla_partido": "SOLIDARIEDADE", "ideologia": "centro"},
    {"sigla_partido": "UNIAO", "ideologia": "centro"},
]


LOAD_ORDER = [
    "deputados",
    "partidos_ideologia",
    "proposicoes_2026",
    "eventos_2026",
    "votacoes_2026",
    "gastos_2026",
    "votacoes_votos_2026",
    "votacoes_orientacoes_2026",
    "votacoes_objetos_2026",
    "proposicoes_temas_2026",
    "eventos_presenca_deputados_2026",
    "proposicoes_autores",
]

ALL_TABLES_ORDERED = LOAD_ORDER[:]


TABLES = {
    "deputados": {
        "file": "deputados.csv",
        "table": "deputados",
        "pk": ["id_deputado"],
        "required": ["id_deputado", "uri_deputado", "nome"],
        "skip_identity": [],
        "transform": "deputados",
        "columns": {
            "uri": ("uri_deputado", C.clean_text),
            "nome": ("nome", C.clean_text),
            "nomeCivil": ("nome_civil", C.clean_text),
            "cpf": ("cpf", C.clean_cpf),
        },
    },
    "partidos_ideologia": {
        "file": None,
        "table": "partidos_ideologia",
        "pk": ["sigla_partido"],
        "required": ["sigla_partido", "ideologia"],
        "skip_identity": [],
        "generated_rows": PARTIDOS_IDEOLOGIA,
        "columns": {
            "sigla_partido": ("sigla_partido", C.clean_party),
            "ideologia": ("ideologia", C.clean_text),
        },
    },
    "proposicoes_2026": {
        "file": "proposicoes-2026.csv",
        "table": "proposicoes_2026",
        "pk": ["id_proposicao"],
        "required": ["id_proposicao", "uri_proposicao"],
        "skip_identity": [],
        "columns": {
            "id": ("id_proposicao", C.clean_int),
            "uri": ("uri_proposicao", C.clean_text),
            "siglaTipo": ("sigla_tipo", C.clean_upper),
            "numero": ("numero", C.clean_int),
            "ano": ("ano", C.clean_int),
            "ementa": ("ementa", C.clean_text),
            "ementaDetalhada": ("ementa_detalhada", C.clean_text),
            "keywords": ("keywords", C.clean_text),
            "ultimoStatus_descricaoSituacao": ("descricao_situacao", C.clean_text),
        },
    },
    "eventos_2026": {
        "file": "eventos-2026.csv",
        "table": "eventos_2026",
        "pk": ["id_evento"],
        "required": ["id_evento"],
        "skip_identity": [],
        "columns": {
            "id": ("id_evento", C.clean_int),
            "uri": ("uri_evento", C.clean_text),
            "dataHoraInicio": ("data_hora_inicio", C.clean_timestamp),
            "dataHoraFim": ("data_hora_fim", C.clean_timestamp),
            "descricaoTipo": ("descricao_tipo", C.clean_text),
            "descricao": ("descricao", C.clean_text),
            "localCamara.nome": ("local_camara", C.clean_text),
        },
    },
    "votacoes_2026": {
        "file": "votacoes-2026.csv",
        "table": "votacoes_2026",
        "pk": ["id_votacao"],
        "required": ["id_votacao"],
        "skip_identity": [],
        "transform": "votacoes",
        "columns": {
            "id": ("id_votacao", C.clean_text),
            "data": ("data_votacao", C.clean_date),
            "siglaOrgao": ("sigla_orgao", C.clean_upper),
            "idEvento": ("id_evento", C.clean_int),
            "aprovacao": ("aprovacao", C.clean_boolean),
            "descricao": ("descricao", C.clean_text),
        },
    },
    "gastos_2026": {
        "file": "Ano-2026.csv",
        "table": "gastos_2026",
        "pk": [],
        "required": ["id_deputado", "nome_parlamentar", "sigla_uf", "sigla_partido", "valor_liquido"],
        "skip_identity": ["id_gasto"],
        "columns": {
            "cpf": ("cpf", C.clean_cpf),
            "nuDeputadoId": ("id_deputado", C.clean_int),
            "txNomeParlamentar": ("nome_parlamentar", C.clean_text),
            "sgUF": ("sigla_uf", C.clean_upper),
            "sgPartido": ("sigla_partido", C.clean_party),
            "vlrDocumento": ("valor_documento", C.clean_money),
            "vlrGlosa": ("valor_glosa", C.clean_money),
            "vlrLiquido": ("valor_liquido", C.clean_money),
            "txtDescricao": ("descricao_despesa", C.clean_text),
            "txtFornecedor": ("fornecedor", C.clean_text),
        },
        "drop_if": "lideranca",
    },
    "votacoes_votos_2026": {
        "file": "votacoesVotos-2026.csv",
        "table": "votacoes_votos_2026",
        "pk": ["id_votacao", "id_deputado"],
        "required": ["id_votacao", "id_deputado", "voto", "nome_deputado"],
        "skip_identity": [],
        "columns": {
            "idVotacao": ("id_votacao", C.clean_text),
            "deputado_id": ("id_deputado", C.clean_int),
            "voto": ("voto", C.clean_vote),
            "deputado_nome": ("nome_deputado", C.clean_text),
            "deputado_siglaPartido": ("sigla_partido", C.clean_party),
            "deputado_siglaUf": ("sigla_uf", C.clean_upper),
        },
    },
    "votacoes_orientacoes_2026": {
        "file": "votacoesOrientacoes-2026.csv",
        "table": "votacoes_orientacoes_2026",
        "pk": ["id_votacao", "sigla_bancada"],
        "required": ["id_votacao", "sigla_bancada"],
        "skip_identity": [],
        "columns": {
            "idVotacao": ("id_votacao", C.clean_text),
            "siglaBancada": ("sigla_bancada", C.clean_party),
            "orientacao": ("orientacao", C.clean_vote),
            "siglaOrgao": ("sigla_orgao", C.clean_upper),
            "descricao": ("descricao", C.clean_text),
        },
    },
    "votacoes_objetos_2026": {
        "file": "votacoesObjetos-2026.csv",
        "table": "votacoes_objetos_2026",
        "pk": [],
        "required": ["id_votacao"],
        "skip_identity": ["id_votacao_objeto"],
        "columns": {
            "idVotacao": ("id_votacao", C.clean_text),
            "proposicao_id": ("id_proposicao", C.clean_int),
            "proposicao_uri": ("uri_proposicao", C.clean_text),
            "proposicao_titulo": ("titulo_proposicao", C.clean_text),
            "proposicao_ementa": ("ementa_proposicao", C.clean_text),
            "proposicao_siglaTipo": ("sigla_tipo_proposicao", C.clean_upper),
            "proposicao_numero": ("numero_proposicao", C.clean_int),
            "proposicao_ano": ("ano_proposicao", C.clean_int),
        },
    },
    "proposicoes_temas_2026": {
        "file": "proposicoesTemas-2026.csv",
        "table": "proposicoes_temas_2026",
        "pk": ["uri_proposicao", "cod_tema"],
        "required": ["uri_proposicao", "cod_tema", "tema"],
        "skip_identity": [],
        "columns": {
            "uriProposicao": ("uri_proposicao", C.clean_text),
            "codTema": ("cod_tema", C.clean_int),
            "tema": ("tema", C.clean_text),
            "relevancia": ("relevancia", C.clean_decimal),
        },
    },
    "eventos_presenca_deputados_2026": {
        "file": "eventosPresencaDeputados-2026.csv",
        "table": "eventos_presenca_deputados_2026",
        "pk": ["id_evento", "id_deputado"],
        "required": ["id_evento", "id_deputado"],
        "skip_identity": [],
        "columns": {
            "idEvento": ("id_evento", C.clean_int),
            "idDeputado": ("id_deputado", C.clean_int),
            "nomeDeputado": ("nome_deputado", C.clean_text),
            "siglaPartido": ("sigla_partido", C.clean_party),
            "siglaUf": ("sigla_uf", C.clean_upper),
        },
    },
    "proposicoes_autores": {
        "file": "proposicoesAutores-2026.csv",
        "table": "proposicoes_autores",
        "pk": [],
        "required": ["id_proposicao", "nome_autor", "tipo_autor"],
        "skip_identity": ["id_autoria"],
        "columns": {
            "idProposicao": ("id_proposicao", C.clean_int),
            "uriProposicao": ("uri_proposicao", C.clean_text),
            "idDeputadoAutor": ("id_deputado", C.clean_int),
            "nomeAutor": ("nome_autor", lambda v: C.clip_text(v, 200)),
            "tipoAutor": ("tipo_autor", C.clean_text),
            "siglaPartidoAutor": ("sigla_partido", C.clean_party),
            "siglaUFAutor": ("sigla_uf", C.clean_upper),
            "ordemAssinatura": ("ordem_assinatura", C.clean_int),
            "proponente": ("peso_autoria", C.clean_decimal),
        },
    },
}
